import json

def build_preview(root, tables, results):
    payload={name:[dict(zip(cols,r)) for r in rows] for name,(cols,_,rows) in tables.items() if name!='DimDate'}
    template='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Healthcare Distribution | Analyst Portfolio</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f2f5f8;color:#182f43;font:15px system-ui}header{background:#122d42;color:white;padding:28px 5%}header small{letter-spacing:2px;color:#88dcd0}h1{font-size:32px;margin:10px 0}header p{color:#bed0dd;max-width:850px;margin:8px 0}.tag{display:inline-block;background:#274459;padding:7px 12px;border-radius:5px;font-size:12px}main{max-width:1300px;margin:auto;padding:25px}.controls{display:flex;flex-wrap:wrap;align-items:center;gap:24px;padding:20px;background:white;border-radius:10px}label{font-size:13px;font-weight:650}select{padding:8px;border:1px solid #ccd7df;border-radius:5px;margin-left:7px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.card,section{background:white;border-radius:10px;padding:22px;border:1px solid #e3e9ed}.card strong{display:block;font-size:29px;margin:10px 0}.card small{color:#637586}.grid{display:grid;grid-template-columns:1.25fr 1fr;gap:20px}h2{font-size:17px;margin:0 0 20px}.barrow{display:flex;align-items:center;gap:10px;margin:18px 0}.barrow b{width:80px;font-size:13px}.track{flex:1;background:#eef3f6;border-radius:4px;height:22px}.fill{background:#138979;height:100%;border-radius:4px}.barrow span{width:70px;text-align:right;font-size:13px}svg{width:100%;height:auto}.scenario{margin-top:20px;background:#e8f4f1}.scenario strong{font-size:26px}.note{font-size:13px;line-height:1.6;color:#536b7b}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:right;padding:12px 8px;border-bottom:1px solid #e5ecef}th:first-child,td:first-child{text-align:left}a{color:#117969}@media(max-width:850px){.cards{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}main{padding:16px}h1{font-size:26px}}</style></head>
<body><header><small>OPERATIONS & FINANCE / ANALYST PORTFOLIO</small><h1>Healthcare Distribution Performance</h1><p>Where do service failures erode contribution, and which interventions deserve investigation?</p><span class="tag">12,000 synthetic orders • 2024–2025</span> <span class="tag">Browser companion preview — not a Power BI screenshot</span></header><main>
<div class="controls"><label>Year <select id="year"><option value="all">All years</option><option>2024</option><option selected>2025</option></select></label><label>Region <select id="region"><option value="all">All regions</option><option>North</option><option>South</option><option>East</option><option>West</option></select></label><label>Assumed avoidable cost <input id="rate" type="range" min="0" max="100" step="5" value="25"> <span id="rateLabel">25%</span></label></div>
<div class="cards"><div class="card">Net revenue<strong id="revenue"></strong><small id="yoy"></small></div><div class="card">Contribution margin<strong id="margin"></strong><small>After modeled variable costs</small></div><div class="card">On-time, in-full<strong id="otif"></strong><small id="count"></small></div><div class="card">Service failure cost<strong id="failure"></strong><small>Late penalties + expedite fees</small></div></div>
<div class="grid"><section><h2>Net revenue by month</h2><div id="trend"></div><p class="note">Monthly order-date totals, USD. Full-year filters prevent partial-period comparisons.</p></section><section><h2>Carrier service level</h2><div id="carriers"></div><p class="note">OTIF = on time AND complete / all fulfilled orders. Compare carrier volumes and lane mix before assigning causes.</p></section></div>
<section class="scenario"><h2>Recovery scenario</h2><strong id="recovery"></strong><p id="scenario"></p><p class="note">A sensitivity scenario, not a forecast or achieved saving. Applies only to late penalties and expedite fees; excludes implementation costs and assumes unchanged revenue, volume and product cost.</p></section>
<section style="margin-top:20px"><h2>Prioritization: service cost by carrier</h2><table><thead><tr><th>Carrier</th><th>Orders</th><th>OTIF</th><th>Failure cost</th><th>Cost / order</th></tr></thead><tbody id="details"></tbody></table></section>
<p class="note">Synthetic, reproducible data. Carrier C is deliberately assigned more delays in the generator. This is a method demonstration, not evidence about real businesses. Power BI source includes 4 dimension relationships, 21 DAX measures, 3 report pages and 21 visuals. <a href="README.md">Read methodology and validation status</a>.</p></main>
<script>const data=__DATA__;
const customers=Object.fromEntries(data.DimCustomer.map(r=>[r.CustomerKey,r]));
const names=Object.fromEntries(data.DimCarrier.map(r=>[r.CarrierKey,r.Carrier]));
const el=id=>document.getElementById(id), usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n), pct=n=>(100*n).toFixed(1)+'%';
function totals(rows){return rows.reduce((a,r)=>{a.net+=r.GrossSales-r.Discount-r.Refund;a.contribution+=r.GrossSales-r.Discount-r.Refund-r.COGS-r.Freight-r.Penalty-r.Expedite;a.failure+=r.Penalty+r.Expedite;a.otif+=r.OnTime*r.InFull;return a},{net:0,contribution:0,failure:0,otif:0})}
function render(){const year=el('year').value,region=el('region').value,rate=+el('rate').value/100;
const rows=data.FactOrders.filter(r=>(year==='all'||r.OrderDate.startsWith(year))&&(region==='all'||customers[r.CustomerKey].Region===region));const t=totals(rows);
el('revenue').textContent=usd(t.net);el('margin').textContent=pct(t.contribution/t.net);el('otif').textContent=pct(t.otif/rows.length);el('failure').textContent=usd(t.failure);el('count').textContent=rows.length.toLocaleString()+' orders in selected period';
const prior=data.FactOrders.filter(r=>r.OrderDate.startsWith(String(+year-1))&&(region==='all'||customers[r.CustomerKey].Region===region));el('yoy').textContent=prior.length?pct(t.net/totals(prior).net-1)+' vs prior year':'Prior-year comparison unavailable';
el('rateLabel').textContent=pct(rate);el('recovery').textContent=usd(t.failure*rate)+' potential gross recovery';el('scenario').textContent='Scenario contribution: '+usd(t.contribution+t.failure*rate)+' | Scenario margin: '+pct((t.contribution+t.failure*rate)/t.net);
const monthly={};rows.forEach(r=>{let m=r.OrderDate.slice(0,7);monthly[m]=(monthly[m]||0)+r.GrossSales-r.Discount-r.Refund});const ms=Object.keys(monthly).sort(),max=Math.max(...Object.values(monthly));
const points=ms.map((m,i)=>[55+i*565/Math.max(ms.length-1,1),220-monthly[m]/max*170]);el('trend').innerHTML='<svg viewBox="0 0 660 260" role="img" aria-label="Monthly net revenue line chart"><line x1="55" y1="220" x2="625" y2="220" stroke="#becdd6"/><text x="8" y="45" fill="#536b7b" font-size="11">'+usd(max/1000)+'k</text><text x="20" y="222" fill="#536b7b" font-size="11">$0</text><polyline fill="none" stroke="#138979" stroke-width="3" points="'+points.map(p=>p.join(',')).join(' ')+'"/>'+points.map((p,i)=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="4" fill="#138979"><title>'+ms[i]+': '+usd(monthly[ms[i]])+'</title></circle>').join('')+'<text x="55" y="247" fill="#536b7b" font-size="12">'+ms[0]+'</text><text x="575" y="247" fill="#536b7b" font-size="12">'+ms.at(-1)+'</text></svg>';
const carriers=data.DimCarrier.map(c=>{const rs=rows.filter(r=>r.CarrierKey===c.CarrierKey);return {name:c.Carrier,n:rs.length,...totals(rs)}}).sort((a,b)=>b.failure-a.failure);
el('carriers').innerHTML=carriers.map(c=>'<div class="barrow"><b>'+c.name+'</b><div class="track"><div class="fill" style="width:'+c.otif/c.n*100+'%"></div></div><span>'+pct(c.otif/c.n)+'</span></div>').join('');
el('details').innerHTML=carriers.map(c=>'<tr><td>'+c.name+'</td><td>'+c.n.toLocaleString()+'</td><td>'+pct(c.otif/c.n)+'</td><td>'+usd(c.failure)+'</td><td>'+usd(c.failure/c.n)+'</td></tr>').join('');}
document.querySelectorAll('select,input').forEach(e=>e.addEventListener('input',render));render();</script></body></html>'''
    (root/'preview.html').write_text(template.replace('__DATA__',json.dumps(payload,separators=(',',':'))),encoding='utf-8')
